# Generated by Django 6.0.3 on 2026-03-10 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ny', models.CharField(blank=True, max_length=100, verbose_name='Name (Chichewa)')),
                ('slug', models.SlugField(help_text="SMS keyword, e.g. 'maize'", unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ny', models.TextField(blank=True)),
                ('icon', models.CharField(default='🌱', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='AgronomyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ny', models.CharField(blank=True, max_length=200)),
                ('body_en', models.TextField()),
                ('body_ny', models.TextField(blank=True)),
                ('season', models.CharField(choices=[('planting', 'Planting Season'), ('growing', 'Growing Season'), ('harvest', 'Harvest Season'), ('any', 'Any Time')], default='any', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='crops.crop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_ny', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('fungal', 'Fungal Disease'), ('viral', 'Viral Disease'), ('bacterial', 'Bacterial Disease'), ('pest', 'Pest / Insect'), ('deficiency', 'Nutrient Deficiency'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('menu_number', models.PositiveSmallIntegerField(help_text='Number farmers type in SMS menu (1, 2, 3...)')),
                ('symptoms_en', models.TextField(help_text='Visible symptoms in English')),
                ('symptoms_ny', models.TextField(blank=True, help_text='Visible symptoms in Chichewa')),
                ('treatment_en', models.TextField(help_text='Recommended treatment in English')),
                ('treatment_ny', models.TextField(blank=True, help_text='Recommended treatment in Chichewa')),
                ('prevention_en', models.TextField(blank=True)),
                ('prevention_ny', models.TextField(blank=True)),
                ('recommended_product', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='crops.crop')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disease / Pest',
                'verbose_name_plural': 'Diseases & Pests',
                'ordering': ['crop', 'menu_number'],
                'unique_together': {('crop', 'menu_number')},
            },
        ),
    ]
