# Generated by Django 6.0.3 on 2026-03-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ny', 'Chichewa')], default='en', max_length=5)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('first_contact', models.DateTimeField(auto_now_add=True)),
                ('last_contact', models.DateTimeField(auto_now=True)),
                ('total_queries', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'ordering': ['-last_contact'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('sent', 'Sent'), ('failed', 'Failed')], default='received', max_length=15)),
                ('intent', models.CharField(blank=True, help_text="Detected intent, e.g. 'crop_disease'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('at_message_id', models.CharField(blank=True, help_text="Africa's Talking message ID", max_length=100)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sms_bot.farmerprofile')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('crop_selected', 'Crop Selected'), ('awaiting_menu', 'Awaiting Menu Choice'), ('language_select', 'Language Selection')], default='idle', max_length=30)),
                ('context', models.JSONField(default=dict, help_text='Current conversation context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sms_bot.farmerprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
    ]
